# Config file for automatic testing at travis-ci.org

language: python
cache: pip
matrix:
  include:
  - python: "3.5"
  - python: "3.6"

install:
  - pip install -r requirements_dev.txt
  - pip install -e .
  - pip install pytest-cov

script:
  - travis_wait 999 pytest --verbose --cov=. confounds/tests/test_confounds.py


